### ISSUE TITLE
[drone] Support creating pull request and push triggers

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#4]
When creating a pipeline in Harness CI, this automation needs to create Pull Request and Push triggers.

TODO: We should also be able to support Tag and Cron events, but those will be tracked in a separate issue. 

Both triggers should ignore commits with [the same skip logic as Drone](https://github.com/harness/drone/blob/master/trigger/skip.go#L80-L82). While only `[CI SKIP]` is in [the documentation](https://docs.drone.io/pipeline/skipping/), Drone supports more patterns. I only tested variations on `[SKIP CI]`, but we should probably support `***NO_CI***` and `***no_ci***` as well.

Also, it is unclear to me if these triggers require input sets. I was unable to get either trigger working without providing an input set.

### Pull Request Trigger

I think Drone only supports `Open`, `Reopen` and `Synchronize` pull request actions, but we should verify.

```yaml
trigger:
  name: Pull Request
  identifier: pullrequest
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  projectIdentifier: example
  pipelineIdentifier: example
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: account.Jim_Sheldon_GitHub
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*SKIP\ CI).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*CI\ SKIP).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*skip\ ci).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*ci\ skip).*$
          headerConditions: []
          repoName: jimsheldon/drone-sandbox
          actions:
            - Open
            - Reopen
            - Synchronize
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - inputs

```

### Push Trigger

```yaml
trigger:
  name: Push
  identifier: push
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  projectIdentifier: example
  pipelineIdentifier: example
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: account.Jim_Sheldon_GitHub
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*\[SKIP\ CI\]).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*\[CI\ SKIP\]).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*\[skip\ ci\]).*$
            - key: <+trigger.payload.head_commit.message>
              operator: Regex
              value: ^(?!.*\[ci\ skip\]).*$
          headerConditions: []
          repoName: jimsheldon/drone-sandbox
          actions: []
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - inputs

```
