### ISSUE TITLE
[drone] Support creating tag triggers

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#7]
When creating a pipeline in Harness CI, this automation needs to create Tag triggers.

## Examples

Harness CI does not currently have built-in Tag triggers, but I successfully tested this workaround.

NOTE: We should verify this workaround with engineering. We could probably do something similar with `payloadConditions`.

### Tag Trigger with pattern

```yaml
trigger:
  name: Tag
  identifier: Tag
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  projectIdentifier: example
  pipelineIdentifier: example
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: account.Jim_Sheldon_GitHub
          autoAbortPreviousExecutions: false
          payloadConditions: []
          headerConditions: []
          jexlCondition: <+trigger.payload.ref> =~ "refs/tags/v.*"
          repoName: jimsheldon/drone-sandbox
          actions: []
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - inputs
```

Which should be the equivalent to this Drone YAML:

```yaml
kind: pipeline
type: docker
name: default

trigger:
  ref:
  - refs/tags/v*
```

### Tag Trigger

```yaml
trigger:
  name: Tag
  identifier: Tag
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  projectIdentifier: example
  pipelineIdentifier: example
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: account.Jim_Sheldon_GitHub
          autoAbortPreviousExecutions: false
          payloadConditions: []
          headerConditions: []
          jexlCondition: <+trigger.payload.ref> =~ "refs/tags/.*"
          repoName: jimsheldon/drone-sandbox
          actions: []
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - inputs
```

Which should be the equivalent to this Drone YAML:

```yaml
kind: pipeline
type: docker
name: default

trigger:
  event:
  - tag
```
