### ISSUE TITLE
[drone] repo connector missing `org.` prefix

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#83]
When passing a token to `drone import`, the org-level SCM connector is created . The resulting `connectorRef` is missing the `org.` prefix.

The repo connector currently downgrades to:

```
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: github
        repoName: drone-testing
```

But since it's at the org level, it should be:

```
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.github
        repoName: drone-testing
```
